# Generated by Django 3.2 on 2023-03-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230330_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Обязательное поле, только цифры, буквы или @/./+/-/_.', max_length=150, null=True, unique=True, verbose_name='Никнеим'),
        ),
    ]
