# Generated by Django 3.2 on 2023-03-31 00:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230330_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.uuid4, max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
