# Generated by Django 3.2 on 2023-04-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_title_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-id'], 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
